#ifndef _GLOBAL_H_
#define _GLOBAL_H_
#include <wx/wx.h>

enum CustomEventId
{
	ENUM_CUSTOMEVENT_ID_PING=9000,
	ENUM_CUSTOMEVENT_ID_PING_EXIT,
	ENUM_CUSTOMEVENT_ID_IPERF_INFO,
	ENUM_CUSTOMEVENT_ID_IPERF_EXIT,

};

BEGIN_DECLARE_EVENT_TYPES()
DECLARE_EVENT_TYPE(ENUM_CUSTOMEVENT_PING, ENUM_CUSTOMEVENT_ID_PING)
DECLARE_EVENT_TYPE(ENUM_CUSTOMEVENT_PING_EXIT, ENUM_CUSTOMEVENT_ID_PING_EXIT)
DECLARE_EVENT_TYPE(ENUM_CUSTOMEVENT_IPERF_EXIT, ENUM_CUSTOMEVENT_ID_IPERF_EXIT)
DECLARE_EVENT_TYPE(ENUM_CUSTOMEVENT_IPERF_INFO, ENUM_CUSTOMEVENT_ID_IPERF_INFO)
END_DECLARE_EVENT_TYPES()


#endif